stages:
  - build

build:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2

  before_script:
    - docker login -u $docker_user -p $pwd
    - docker info
  script:
    - docker build -t registry.gitlab.com/humayun-rashid/scoreboard:latest .
    - docker push registry.gitlab.com/humayun-rashid/scoreboard:latest
