version: "2"
services:
  app:
    container_name: scoreboard
    restart: always
    build: .
    ports:
    - "8080:8080"
    links:
    - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
    - "27017-27019:27017-27019"