###
POST http://localhost:8080
Content-Type: application/json

{
    "name": "Player 7",
    "score": "421"
}

###
GET http://localhost:8080
###
GET http://localhost:8080/des
###
GET http://localhost:8080/date
###
GET http://localhost:8080/5e9c60c880dd1132c6cb8a38

###
GET  http://localhost:8080/name
Content-Type: application/json

{
    "name": "Player 3"
}

###
DELETE http://localhost:8080
```
Content-Type: application/json

{
    "name": "Player 3"
}
```
}
###
DELETE http://localhost:8080/5e9c60c880dd1132c6cb8a38
