###
POST http://localhost:8080
Content-Type: application/json

{
    "name": "deo",
    "score": "800"
}

###
GET http://localhost:8080
###
GET http://localhost:3000/des
###
GET http://localhost:3000/date
###
GET http://localhost:3000/5e9b6f4969ef057642bc2802

###
GET  http://localhost:3000/name
Content-Type: application/json

{
    "name": "deo"
}

###
DELETE http://localhost:3000
Content-Type: application/json

{
    "name": "deo"
}
###
DELETE http://localhost:3000/5e9b6f4669ef057642bc2801
